build:
    environment:
        php:
            version: 5.5.0
             ini:
                'date.timezone': 'Europe/Moscow'

checks:
    php: true

filter:
    excluded_paths:
        - tests/*