build:
    environment:
        php:
            version: 5.6.16

before_commands:
  - composer install --prefer-source --no-interaction --dev

checks:
   php:
      uppercase_constants: true
      return_doc_comments: true
      remove_extra_empty_lines: true
      properties_in_camelcaps: true
      parameters_in_camelcaps: true
      parameter_doc_comments: true
      classes_in_camel_caps: true
      code_rating: true
      duplication: true

filter:
    excluded_paths:
        - tests/*