language: php
 
php:
  - 5.5
  - 5.6
  - hhvm
 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token:
      secure: "ZGX5EDYGgxnZVbN1IgVoJNQXym5iel1i4mlbdd4835pXH8dErU6r+DkkccU4CgVKlAb0XILUZ4PtihnvGq/Q7h47QjpVoQx0pkeBhb8zwedvqN80TVHN132+y52Lsknp+9Ajq4AWC/qpvWGgSDTXpq/OPAREtOnut2qibmBcCdIWkWAkwBx26zQk2pgqUHHdgD3piCoHMM//59iNxYix6jHTB09OPrHu9TaIxR1k1UJ3v4Iq4GLJOWczn0fcYFHzd+W6e4OmSBv5/Me7/KCK5RuY8q9LjIdysND0cWhlfN8wbihXJi0iPjdTP1idvDYbNZmN4C1t9OEBnH5FKcvlhtqoHCinuysUaET035WG2eIAR7dF/a7Bgxh1x2RC6jjHy3UDBsgRhGwiicdllvn4S3ErOwi9prGihiPOadrbBOauakza6OhmUMpYO1rBNDH3w4GKvTmQKX4f9Cmz4KCXJY2Oo6dHsAEI102EoBiKxRQLKdQIo4gG4VqU6LwECR5zl5LnpeLuuATnVecYiilbcmbPk2Sii14QDgZ2OQ8YqPG9FSsgFEMtwpKbGgl8gAp1ZFW1XIgg8iH0eZsx4++ew3QxSaIekLOhtRZ5+Dx6DsCd0+HbC18TJNNa4gxt5986nWUdxL0OqXNspXMlK2xHZjy0nHQqQW8j4nD2jvqZyyM="
