language: php
 
php:
  - 5.5
  - 5.6
  - hhvm
 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit

addons:
  code_climate:
    repo_token: 5ee678fadd1d4bb7bece6a4504820773a5bf1ecf090a82bce1634dd87b91a462