language: php
 
php:
  - 5.5
  - 5.6

addons:
  code_climate:
    repo_token:
      secure: "PXHxPoCkPuUSDUeKlW5oQEbv0aW/VhtW9xH5ZUgSal5acqdNb1bgzqc7UneFviwzEl3o6tgiExEnj4wF6YJ71PYng2GORoF/bThgUwLqEiQyHBMJYPmMiE5rdABTdKYecWm21dB7onhr2+U+szymwTsJuVCybc6Yvy6BnvGkByOhijn21QP90Tku8MmdSn+HUYttIK8zPXtGfXGqF8KIEVArREhQsuxrgDroS5obZyTxMXtaEcLceOGnaXOh1ZHP+e2pfzKAvq5idiYkJ7XlL3pyAgv2gvlnc9Z4288CRQmFymVDlF0PemHhPS4tk9pJqOPxJriQxVCFZMp1ddvAmJEeY5MZ0oEez9Zo6LEgZCLw1v8GPs5vXVzE83FlfWrc7utfmH6QxBFqv/1uY/z0eTWURkhakRFjbwST+jFTu4BjFxRkCK64jkxokdpWweYvV78XYTF9XdyZGa5JGz4VaEFIFoNgqUm5oechnWOLuKzpXlu+J1cN0GW3QcLQErFpuRy8Fiqrfi+zFPuRQEYwpfCdW4yoJvysJTuRen7C4kT6KQzCkoiH50rTrlAxHHabgu8G70wODehQU+Sn/+FoOQN8gV8Toy8oqTamd1Ki6YmQmGndgGJLbR62Ob8d3EOnZO2h8/sKU5IpO/TyZjCVR6E1nDocDBsdeX4jKZTg1yg="

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit

after_script:
  - vendor/bin/test-reporter

